mytemplateengine/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'main'
urlpatterns = [
        path('', views.Index.as_view(), name='index'),
        path('login', views.LoginUser.as_view(), name='login'),
        path('logout', views.LogoutUser.as_view(), name='logout'),
        path('register', views.RegisterUser.as_view(), name='register'),
        path('createbanner/', views.create_banner, name='createbanner'),
        path('createbanner/preresult', views.preresult_html, name='preresult'),
        path('createbanner/result', views.result_html, name='result'),
        path('createbanner/oldresult', views.result_html, name='oldresult'),
        path('createtransfer/', views.create_transfer, name='createtransfer'),
        path('createtransfer/pretransfer', views.pretransfer_html, name='pretransfer'),
        path('createtransfer/resulttranfer', views.result_transfer, name='resulttranfer'),
        path('showbase', views.create_base, name='showbase'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytemplateengine/mytemplateengine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

mytemplateengine/main/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models

''' модели для создания пользователя и входа '''
class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Почтовый адрес должен быть задан')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields['is_staff'] = False
        extra_fields['is_superuser'] = False
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('Почтовый адрес', max_length=50, db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'

    objects = UserManager()


''' модель для главной страницы '''
class Mainindex(models.Model):
    get_user_model()
    title = models.CharField('Название', max_length=50)

    class Meta:
        verbose_name = 'Главная'
        verbose_name_plural = 'Главная страница'


''' Модель для выбора клиентов по купленным событиям '''
class Events(models.Model):
    name_event = models.CharField('Название мероприятия', max_length=150)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория мероприятия')

    def __str__(self):
        return self.name_event


class Category(models.Model):
    name_category = models.CharField(max_length=20, db_index=True)

    def __str__(self):
        return self.name_category


class Client(models.Model):
    post_mail = models.EmailField('Почта', max_length=150)
    number_phone = models.CharField('Номер телефона', max_length=20)
    date_registratiom = models.DateField('Дата регистрации', auto_now=True)
    buy_ticket = models.ForeignKey('Events', verbose_name='купленные билеты', on_delete=models.PROTECT)
    category_event = models.ForeignKey('Category', verbose_name='категория купленных билетов', on_delete=models.PROTECT)

    def __str__(self):
        return self.post_mail

mytemplateengine/main/views.py
import json
import logging
import csv
from io import BytesIO
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, FileResponse
from django.shortcuts import reverse, render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from .models import Mainindex, Client
from .form import LoginUserForm, RegisterUserForm, PreCreateBanner, ContentForm, TransferForm, \
    PreTransferForm, CreateBannerPoster, ChoiseFilterModel
from django.views.generic import CreateView, ListView
from .servises import created_mailing_list, unpack, unpuck_banner


logger = logging.getLogger(__name__)

''' класс входа по логину '''
class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'main/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def get_success_url(self):
        return reverse('main:index')


class LogoutUser(LogoutView):
    next_page = reverse_lazy('main:index')


''' класс регистрации на сайте '''
class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'main/register.html'
    success_url = reverse_lazy('main:login')

    def get_context_date(self, **kwargs):
        context = super().get_context_date(**kwargs)
        context['title'] = 'Регистрация'
        return context


''' класс перевода формы URL '''
class Index(ListView):
    model = Mainindex
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Шаблонизатор'
        return context


''' функции для создания индивидуальной рассылки '''
def create_banner(request):
    context = {}
    if request.method == 'POST':
        form = PreCreateBanner(request.POST)
        if form.is_valid():
            try:
                context['url'] = []
                context['url'].append({
                    'banner_url': form.cleaned_data.get('banner_url'),
                })
                with open('json_url.json', 'w', encoding='utf-8') as file:
                    json.dump(context, file, indent=4)
                return redirect('main:preresult', permanent=True)
            except:
                form.errors(None, 'Ошибка добавления афиши')
    else:
        form = PreCreateBanner()

    context = {
        'title': 'Создание баннеров',
        'form': form,
        }

    return render(request, 'main/createbanner.html', context)


def preresult_html(request):
    created_mailing_list()
    with open('json_content.json', 'r', encoding='utf8') as file:
        file = json.load(file)
        content = {}
        for url in file['content0']:
             content.update(url)

    form = PreCreateBanner(initial=content)
    form2 = CreateBannerPoster(initial=content)
    form3 = ContentForm(initial=content)
    context = {
        'title': 'Редактирование баннеров',
        'form': form,
        'form2': form2,
        'form3': form3,
        }

    if request.method == 'POST':
        form = PreCreateBanner(request.POST, initial=content)
        form2 = CreateBannerPoster(request.POST, initial=content)
        form3 = ContentForm(request.POST, initial=content)

        if form.is_valid() and form2.is_valid() and form3.is_valid():
            try:
                content = {}
                content['content'] = []
                content['content'].append({
                    'banner_date': form.cleaned_data,
                    'banner_title_content': form2.cleaned_data,
                    'banner_content': form3.cleaned_data,
                })
                with open('json_content.json', 'w', encoding='utf8') as file:
                    json.dump(content, file, indent=4)

                update_type = request.POST.get('update_type')
                if update_type == 'download':
                    is_dict = unpuck_banner(content)
                    if is_dict['is_newsite'] == True:
                        myfile = render_to_string('main/result.html', is_dict)
                        f = BytesIO(myfile.encode('utf-8'))
                        return FileResponse(f, as_attachment=True, filename=f"{is_dict['date_poster']}.html")
                    else:
                        myfile = render_to_string('main/oldresult.html', is_dict)
                        f = BytesIO(myfile.encode('utf-8'))
                        return FileResponse(f, as_attachment=True, filename=f"{is_dict['date_poster']}.html")
                return redirect('main:result')
            except:
                form.errors(None, 'Ошибка редактирования афиши')
    else:
        form = PreCreateBanner()
        form2 = CreateBannerPoster()
        form3 = ContentForm()

    return render(request, 'main/preresult.html', context)


def result_html(request):
    context = {}
    is_dict = unpuck_banner(context)
    if is_dict['is_newsite'] == True:
        return render(request, 'main/result.html', is_dict)
    else:
        return render(request, 'main/oldresult.html', is_dict)


''' создание технической рассылки '''
def create_transfer(request):
    context = {}
    if request.method == 'POST':
        form = PreCreateBanner(request.POST)
        if form.is_valid():
            try:
                context['url'] = []
                context['url'].append({
                    'banner_url': form.cleaned_data.get('banner_url'),
                })
                with open('json_url.json', 'w', encoding='utf-8') as file:
                    json.dump(context, file, indent=4)
                return redirect('main:pretransfer', permanent=True)
            except:
                form.errors(None, 'Ошибка добавления афиши')
    else:
        form = PreCreateBanner()

    context = {
        'title': 'Перенос мероприятия',
        'form': form,
        }

    return render(request, 'main/createtransfer.html', context)


def pretransfer_html(request):
    created_mailing_list()
    with open('json_content.json', 'r', encoding='utf8') as file:
        file = json.load(file)
        content = {}
        for url in file['content0']:
            content.update(url)

    form = PreTransferForm(initial=content)
    form2 = TransferForm(initial=content)
    context = {
        'title': 'Редактирование технической рассылки',
        'form': form,
        'form2': form2,
    }

    if request.method == 'POST':
        form = PreTransferForm(request.POST)
        form2 = TransferForm(request.POST)
        if form.is_valid() and form2.is_valid():
            try:
                content = {}
                content['content'] = []
                content['content'].append({
                    'transfer': form.cleaned_data,
                    'transfer_date': form2.cleaned_data
                })
                with open('json_content.json', 'w', encoding='utf8') as file:
                    json.dump(content, file, indent=4)

                update_type = request.POST.get('update_type')
                if update_type == 'download':
                    is_dict = unpack(content)
                    if is_dict['is_newsite'] == True:
                        myfile = render_to_string('main/resulttransfer.html', is_dict)
                        f = BytesIO(myfile.encode('utf-8'))
                        return FileResponse(f, as_attachment=True, filename=f"{is_dict['date_poster']}.html")
                    else:
                        myfile = render_to_string('main/oldresulttranfer.html', is_dict)
                        f = BytesIO(myfile.encode('utf-8'))
                        return FileResponse(f, as_attachment=True, filename=f"{is_dict['date_poster']}.html")
                return redirect('main:resulttranfer')
            except:
                form2.errors(None, 'Ошибка редактирования афиши')

    else:
        form = PreTransferForm()
        form2 = TransferForm()

    return render(request, 'main/pretransfer.html', context)


def result_transfer(request):
    context = {}
    is_dict = unpack(context)

    if is_dict['is_newsite'] == True:
        return render(request, 'main/resulttransfer.html', is_dict)
    else:
        return render(request, 'main/oldresulttranfer.html', is_dict)


''' класс для выбора базы '''
@login_required
def create_base(request):
    form = ChoiseFilterModel()
    ss = []
    if request.method == 'POST':
        filters = {}
        for key, value in request.POST.items():
            if key in ['buy_ticket', 'category_event']:
                filters[key] = value
                ss.append(Client.objects.filter(**filters))
                response = HttpResponse(content_type='text/csv')
                writer = csv.writer(response)
                writer.writerow(['Client', 'Email'])
                for member in ss:
                    writer.writerow(member)
                response['Content-disposition'] = "attachment; filename='Client.csv'"
                return response
    else:
        form = ChoiseFilterModel()

    context = {
        'title': 'выбор базы',
        'form': form,
    }

    return render(request, 'main/showbase.html', context)

# def view_404(request, exception=None):
#     return redirect('/')

mytemplateengine/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/normalize.css' %}" rel="stylesheet">
</head>
<body>
    
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <div class="d-flex justify-content-start">
                <a href="{% url 'main:index' %}" class="navbar-brand d-flex align-items-center">
                    <strong>Шаблонизатор</strong>
                </a>
            </div>
            <div class="d-flex justify-content-end">
            {% if request.user.is_authenticated %}
                    <a href="{% url 'main:showbase' %}" class="navbar-brand"><strong>выбрать базу клиентов</strong></a>
                    <strong class="navbar-brand">{{ user.email }}</strong>
                    <strong class="navbar-brand"> | </strong>
                    <a href="{% url 'main:logout' %}" class="navbar-brand"><strong>Выйти</strong></a>
                {% else %}
                    <a href="{% url 'main:register' %}" class="navbar-brand"><strong>Регистрация</strong></a>
                    <strong class="navbar-brand"> | </strong>
                    <a href="{% url 'main:login' %}" class="navbar-brand"><strong>Войти</strong></a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<main>
    {% block section %}{% endblock section %}
    {% block content %}{% endblock content %}

</main>

</body>
</html>

mytemplateengine/main/templates/main/base_result.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="https://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title_poster }}</title>

    <style type="text/css">
        body { Margin: 0; padding: 0; min-width: 100%; background-color: #ffffff; }
        a { text-decoration-color: #181818; text-decoration: none;     }
        td { padding: 0; }
        img { border: 0; }
        .wrapper { width: 100%; table-layout: fixed; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
        .webkit { max-width: 600px; }

        /* Windows Phone Viewport Fix */
        @-ms-viewport {
            width: device-width;
        }
        @media screen and (min-width: 520px) {
            .two-column .column { max-width: 50% !important; }
            .four-column .column { max-width: 25% !important; }
            .three-column .column { max-width: 33% !important; }
        }
        @media screen and (min-width: 450px) and (max-width: 519px) {
            .two-column .column { max-width: 50% !important; }
            .three-column .column { max-width: 100% !important; }
            .four-column .column { max-width: 25% !important; }
        }
        @media screen and (max-width: 449px) {
            .two-column .column { max-width: 110px !important; }
            .three-column .column { max-width: 100% !important; }
            .four-column .column { max-width: 25% !important; }
        }
        @media screen and (max-width: 350px) {
            .four-column .column { max-width: 50% !important; }
        }
    </style>
    <!--[if (gte mso 9)|(IE)]>
    <style type="text/css">
        table { border-collapse: collapse !important; }
    </style>
    <![endif]-->
</head>
<body align="center" style="margin:0; padding:0; min-width:100%; background: #f7f7f7; font-family: Helvetica, Geneva, sans-serif;">
    <div style="background: #f7f7f7;">
        <div style="margin: 0 auto; max-width:600px; background: #fff; padding-bottom: 20px;">

<!-------------------HEADER---------------------->
<div style="padding: 20px 20px 0">
    <div
        style="color: #919191; font-size: 12px; line-height: 14px; letter-spacing: 0.4px; text-align: center;">
        Если письмо отображается некорректно, то <a
            href="https://cdn.kassy.ru/mailing/{{ date_poster }}/?subdivision={{subdivision}}&dispatch_id={{dispatch_id}}&email={{email}}&token={{token}}&user_id={{user_id}}&utm_source=cdn&utm_medium=email&utm_campaign=email_delivery_{{ date_poster }}&utm_content=direct&utm_term=link_cdn{{ labels }}"
            target="_blank"
            style="text-decoration: underline; color: #919191; letter-spacing: 0.4px;">смотрите здесь</a>
    </div> <a
        href="https://{{subdivision}}.kassy.ru/?utm_source=cdn&utm_medium=email&utm_campaign=email_delivery_{{ date_poster }}&utm_content=direct&utm_term=link_kassy_main{{ labels }}"
        target="_blank"
        style="display: block; font-size: 0; background: #ae5dea url('img/rassylka_fon.jpg'); text-align: center; padding: 11px 0; margin-top: 20px;">
        <img src="https://cdn.kassy.ru/mailing/{{ date_poster }}/img/rassylka.png"></a> </a>
    <div
        style="text-align: center; font-size: 17px; line-height: 20px; font-family: Helvetica, Geneva; padding: 7px 0 8px; margin: 0 0 30px; background: #a349e8; ">
        <table style="font-family: Helvetica, Geneva, sans-serif; border-collapse: collapse; width: 60%;"
            align="center">
            <tr>
                <td style="padding: 0 10px;"> <a
                        href="https://{{subdivision}}.kassy.ru/events/koncerty-i-shou/?utm_source=cdn&utm_medium=email&utm_campaign=email_delivery_{{ date_poster }}&utm_content=direct&utm_term=link_nav_koncerty_i_shou{{ labels }}"
                        target="_blank" style="color: #fff; text-decoration: none;">Концерты</span></a>
                </td>
                <td style="padding: 0 10px;"> <a
                        href="https://{{subdivision}}.kassy.ru/events/teatr/?utm_source=cdn&utm_medium=email&utm_campaign=email_delivery_{{ date_poster }}&utm_content=direct&utm_term=link_nav_teatr{{ labels }}"
                        target="_blank" style="color: #fff; text-decoration: none;">Театр</a> </td>
                <td style="padding: 0 10px;"> <a
                        href="https://{{subdivision}}.kassy.ru/events/cirk/?utm_source=cdn&utm_medium=email&utm_campaign=email_delivery_{{ date_poster }}&utm_content=direct&utm_term=link_nav_cirk{{ labels }}"
                        target="_blank" style="color: #fff; text-decoration: none;">Цирк</a> </td>
                <td style="padding: 0 10px;"> <a
                        href="https://{{subdivision}}.kassy.ru/events/kino/?utm_source=cdn&utm_medium=email&utm_campaign=email_delivery_{{ date_poster }}&utm_content=direct&utm_term=link_nav_kino{{ labels }}"
                        target="_blank" style="color: #fff;text-decoration: none;">Кино</a> </td>
            </tr>
        </table>
    </div>
</div>


{% block content %}{% endblock content %}

<!-------------------FOOTER---------------------->
            <div style="background: #a349e8 url('img/bg.jpg'); padding: 16px 16px; margin: 40px 20px 0;">
                <table width="100%" style="border-collapse: collapse; font-family: Helvetica, Geneva, sans-serif; color: #fff; font-size: 16px; line-height: 22px;">
                    <tr>
                        <td colspan="2" valign="top">
                            <table style="border-collapse: collapse; width: 100%;">
                                <tr>
                                    <td style="min-width: 200px;" valign="top" align="left">
                                        <img src="https://cdn.kassy.ru/mailing/{{ date_poster }}/img/rassylka.png" style="width: 175px;">
                                    </td>
                                    <td align="right" valign="top">
                                        <a href="https://www.tiktok.com/@kassy.ru?" target="_blank" style="text-decoration:none; display: inline-block; vertical-align: top; margin: 0 0 10px 10px;">
                                            <img src="https://cdn.kassy.ru/mailing/{{ date_poster }}/img/tik_tok.png" width="50"  alt="TikTok" title="TikTok" style="border-width:0;">
                                        </a>
                                        <a href="https://t.me/newskassyru" target="_blank" style="text-decoration:none; display: inline-block; vertical-align: top; margin: 0 0 10px 10px;">
                                            <img src="https://cdn.kassy.ru/mailing/{{ date_poster }}/img/telegram.png" width="50"  alt="telegram" title="telegram" style="border-width:0;">
                                        </a>
                                    </td>
                                </tr>
                            </table>


                        </td>
                    </tr>
                    <tr>
                        <td valign="bottom" align="left" style="padding: 0; height: 115px;">
                            <a href="mailto:service@kassy.ru?subject=Message from mailing kassy.ru" style="color: #fff; text-decoration: none;" target="_blank">Обратная связь</a>
                        </td>
                        <td align="right" valign="bottom" style="padding: 0;">
                            <a href="{{ number_phone_liks }}" style="text-decoration:none; color: #fff;"><b style="font-size: 25px; font-family: Tahoma, sans-serif; line-height: 29px;">{{ number_phone }}</b><br>Справочная служба</a>
                        </td>
                    </tr>
                </table>
            </div>
            <div>
                <table width="100%" style="border-collapse: collapse; font-family: Helvetica, Geneva, sans-serif; color: #fff; font-size: 10px; line-height: 10px;">
                    <tr>
                        <td align="center" valign="top" style="padding:10px 0px 10px 0px; font-family: Tahoma, Geneva, sans-serif; color:#919191; width:60%; font-size:10px; line-height: 18px;">
                            <span style="font-family:  Tahoma, Geneva, sans-serif; color:#919191; font-size: 10px; line-height: 14px;"> Вы получили это сообщение, т.к. являетесь зарегистрированным пользователем сайта {{subdivision}}.kassy.ru и согласились получать информационные письма kassy.ru. Если вы не хотите получать рассылку, перейдите по ссылке
                                <a style="color: #919191; text-decoration: revert;" href="https://{{subdivision}}.kassy.ru/dispatch/unsubscribe/?dispatch_id={{dispatch_id}}&email={{email}}&token={{token}}&user_id={{user_id}}&utm_source=cdn&utm_medium=email&utm_campaign=email_delivery_{{ date_poster }}&utm_content=direct&utm_term=link_unsubscribe" target="_blank">
                                    отписаться.<span style="white-space:nowrap"></span>
                                </a>
                            </span>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <img style="height: 1px; width: 1px;" src="https://{{subdivision}}.kassy.ru/dispatch/view_{{dispatch_id}}.png?email={{email}}&token={{token}}" alt="">
</body>

</html>

mytemplateengine/main/templates/main/createbanner.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<div class ="container px-4 py-3" id="featured-3">
    <h2 class="fpb-2 border-bottom">Ссылка на афишу</h2>
</div>
{% endblock section %}

{% block content %}
<div class="album py-5">
    <div class="container d-flex flex-column align-items-center justify-content-center">
        <form action="" class="d-flex flex-column mb-3" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
                {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
            <button class="btn btn-primary align-items-center" type="submit">Передать данные</button>
        </form>
    </div>
</div>
{% endblock %}

mytemplateengine/main/templates/main/createtransfer.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<div class ="container px-4 py-5" id="featured-3">
    <h2 class="fpb-2 border-bottom">Ссылка на то, что у нас переносится или отменено</h2>
</div>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex flex-column align-items-center justify-content-center">
        <form action="" class="d-flex flex-column mb-3" enctype="multipart/form-data" method="post">
            {% csrf_token %}
                {% for f in form %}
                <div class="col-md-auto">
                    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                </div>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
            <button class="btn btn-primary" type="submit">Передать данные</button>
        </form>
    </div>
</div>

{% endblock %}

mytemplateengine/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
{% endblock section %}

{% block content %}

<div class="container px-4 py-5" id="hanging-icons">
  <h2 class="pb-2 border-bottom">Выбор рассылок</h2>
  <div class="row g-3 py-5 row-cols-1 row-cols-lg-3">
    <div class="col d-flex align-items-start">
      <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
      </div>
      <div>
        <h2>Индивидуальная</h2>
        <p>Только баннеры и ничего больше, возможно текст)</p>
        <a href="{% url 'main:createbanner' %}" class="btn btn-primary">
          Выбрать афиши
        </a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
      </div>
      <div>
        <h2>Техническая</h2>
        <p>Только текст только хардкор</p>
        <a href="{% url 'main:createtransfer' %}" class="btn btn-primary">
          Что переносится?
        </a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

mytemplateengine/main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<div class ="container px-4 py-5" id="featured-3">
    <h2 class="fpb-2 border-bottom">Авторизуйся</h2>
</div>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex justify-content-center">
        <form method="post" class="d-flex flex-column w-50">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal text-center">Войти на сайт</h1>
            <strong class="text-danger">{{ form.non_field_errors }}</strong>
            {% for widget in form %}
                <div class="form-floating mb-3">
                    {{ widget }}
                    {{ widget.label_tag }}
                </div>
                    {% if widget.errors %}
                        <ol>
                            {% for error in widget.errors %}
                            <li><strong class="text-danger">{{ error }}</strong></li>
                            {% endfor %}
                        </ol>
                    {% endif %}
            {% endfor %}
            <button class="w-25 btn btn-lg btn-primary" type="submit">Войти</button>
        </form>
    </div>

</div>
{% endblock content %}

mytemplateengine/main/templates/main/pretransfer.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<div class ="container px-4 py-5" id="featured-3">
    <h2 class="fpb-2 border-bottom">Редактируем рассылку</h2>
</div>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex flex-column align-items-left justify-content-center">
        <form action="" class="d-flex flex-column mb-3" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{form.errors}}
            {{ form.non_field_errors }}
                {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                {{ form2.as_p }}
                {{ form2.errors }}
            <input type="checkbox" name="update_type" value="download">хочу скачать</input></br>
            <button class="btn btn-primary justify-content-center">Собрать</button>

        </form>
    </div>
</div>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

</form>

{% endblock %}

mytemplateengine/main/templates/main/register.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<div class ="container px-4 py-5" id="featured-3">
    <h2 class="fpb-2 border-bottom">Зарегистрируйся</h2>
</div>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex justify-content-center">
        <form method="post" class="d-flex flex-column w-50">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal text-center">Введите данные нового пользователя</h1>
            <strong class="text-danger">{{ form.non_field_errors }}</strong>
            {% for widget in form %}
                <div class="form-floating mb-3">
                    {{ widget }}
                    {{ widget.label_tag }}
                </div>
                    {% if widget.errors %}
                        <ol>
                            {% for error in widget.errors %}
                            <li><strong class="text-danger">{{ error }}</strong></li>
                            {% endfor %}
                        </ol>
                    {% endif %}
            {% endfor %}
            <button class="w-25 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
        </form>
    </div>

</div>
{% endblock content %}